### ISSUE TITLE
Withdrawable text to orange alt color

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/ont-stake#13]
When there is ONT in the withdraw-able state, it's not making money and probably safest to be moved back to the wallet asap as there is nothing else you can really do with it here anyway.
For the staked nodes list view, can we update the withdraw-able text to be the orange color we have been using to make it pop a little more. 

<img width="653" alt="screen shot 2019-01-15 at 2 53 53 pm" src="https://user-images.githubusercontent.com/16552874/51161356-6b5f0200-18d5-11e9-9dce-1fd81510f7b7.png">

Update to:
<img width="798" alt="screen shot 2019-01-15 at 2 55 30 pm" src="https://user-images.githubusercontent.com/16552874/51161408-9e08fa80-18d5-11e9-9570-f31939fc549e.png">

**Comment by nickfujita** [comment]
Updated in b6bd2694a7c617c4ecb6d3d73b013d0d67eb8d33
