### ISSUE TITLE
Withdrawable to Withdraw-able

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/ont-stake#14]
I don't think withdrawable is actually a word. 
Do a find and replace and add a hyphen in so it's withdraw-able

**Comment by nickfujita** [comment]
Withdrawable appears to a valid form of withdraw:

https://www.dictionary.com/browse/withdrawable

```
Derived Forms
withdrawable , adjective
withdrawer , noun
```

Not sure why the OS spelling correction doesn't have it.

**Comment by nickfujita** [comment]
Also not sure how reliable dictionary.com is, but I think it might be listed under a British listing? :shrug:

**Comment by creyeknife** [comment]
yeah no worries. I thought it was a real word but kept telling me it wasn't
