### ISSUE TITLE
Helper text styles update

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/ont-stake#15]
Make all text white, make heading bold and description regular (Swap the current styles).

<img width="358" alt="screen shot 2019-01-15 at 3 32 22 pm" src="https://user-images.githubusercontent.com/16552874/51162764-c515fb00-18da-11e9-9abe-ebe4b29f12ad.png">

Update to:
<img width="396" alt="screen shot 2019-01-15 at 3 33 27 pm" src="https://user-images.githubusercontent.com/16552874/51162826-ebd43180-18da-11e9-845b-24cbc9e3a446.png">

**Comment by nickfujita** [comment]
Fixed in 8c1290d07ecd5e5b5a20a30c666eb7776b12d4ce
