### ISSUE TITLE
Margins are not consistent between views.

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/ont-stake#8]
The left, top and right margins are a bit different between each screen

<img width="314" alt="screen shot 2019-01-15 at 12 27 30 pm" src="https://user-images.githubusercontent.com/16552874/51156916-09949d00-18c1-11e9-8c3c-bfc5b1d9394f.png">

<img width="249" alt="screen shot 2019-01-15 at 12 27 24 pm" src="https://user-images.githubusercontent.com/16552874/51156915-09949d00-18c1-11e9-9977-0a8eb5d4bd44.png">

<img width="434" alt="screen shot 2019-01-15 at 12 27 37 pm" src="https://user-images.githubusercontent.com/16552874/51156917-0a2d3380-18c1-11e9-9b5e-b0bbee8c42dc.png">

The left and right should always be 20pt 

The top shifts a little due to content. 
Home page top is 30pt for the logo header
The secondary pages with back button are 40pt at the top

Also, the staketolgy logo is not left aligned with the content on the home page.

**Comment by nickfujita** [comment]
Fixed in https://github.com/O3Labs/ont-stake/commit/20bf083cf0ae7f24c38a4add05a4545c5f0b0359
