### ISSUE TITLE
Popup text for withdraw is misleading

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/ont-stake#9]
It says it will be withdrawn next staking round but is actually instant because it was pending still.
<img width="808" alt="screen shot 2019-01-15 at 12 47 25 pm" src="https://user-images.githubusercontent.com/16552874/51160241-7499a000-18d0-11e9-89ac-bdb7d44d305e.png">

Short of making it have multiple states, maybe we can just remove the second line about being available in the next round. So just say "500 ONT has been requested to be withdrawn."

If you feel it needs more, maybe could add "Please wait a moment for it to update" or something? Not sure it's needed though.

**Comment by nickfujita** [comment]
Fixed in 2573bf70de850a2b51166f3e61bd8447b3c2607a
